apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pmge
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pmge
    app.kubernetes.io/part-of: tkwch-fix-0075-0067-app
  name: devfile-sample-pmge
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pmge
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pmge
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0067-tenant/tkwch-fix-0075-0067-app/devfile-sample-pmge@sha256:217aa1b99ced7be6d2f024797ee6583a197239c072a1fdbad5196c665372e28e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
